'use strict';
const ST=[[-1,0],[0,1],[1,0],[0,-1]],CW=d=>(d+1)%4,CCW=d=>(d+3)%4,COL=['#00cec9','#fdcb6e','#e17055','#74b9ff'];
const CFG={easy:{n:5,min:7,par:10},medium:{n:7,min:14,par:15},hard:{n:10,min:25,par:22},expert:{n:13,min:40,par:30}};
const BASE=1000,MIS=-25,EX=-10,HINT=-75,LP=2,LPBASE=50,LPPT=5,LPCAP=1.4,SPD=200,SPDCAP=-300,BEST='redirect_html_best_v2';
let G=[],N=7,S=[0,0],E=[0,0],sol=[],score=BASE,moves=0,miss=0,excess=0,hints=0,rot=new Map(),start=0,done=false,hint=null,timer=null,best={};
const $=id=>document.getElementById(id),cv=$('c'),x=cv.getContext('2d');
function fmt(t){return Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}function sig(n){return n>0?'+'+n:String(n)}function key(r,c){return r+','+c}function inside(r,c){return r>=0&&c>=0&&r<N&&c<N}function same(a,b){return a&&b&&a[0]===b[0]&&a[1]===b[1]}function dir(a,b){let dr=b[0]-a[0],dc=b[1]-a[1];return dr<0?0:dc>0?1:dr>0?2:3}function shuf(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function borderCell(){let s=Math.floor(Math.random()*4),k=Math.floor(Math.random()*N);return s===0?[0,k]:s===1?[k,N-1]:s===2?[N-1,k]:[k,0]}function isBorder(p){return p[0]===0||p[1]===0||p[0]===N-1||p[1]===N-1}
function makePath(){for(let tries=0;tries<500;tries++){let st=borderCell(),seen=new Set([key(...st)]),p=[st],out=null;function dfs(r,c){if(p.length>=CFG[$('diff').value].min&&isBorder([r,c])&&!same([r,c],st)){out=p.slice();return true}for(const d of shuf([0,1,2,3])){let nr=r+ST[d][0],nc=c+ST[d][1],k=key(nr,nc);if(!inside(nr,nc)||seen.has(k))continue;seen.add(k);p.push([nr,nc]);if(dfs(nr,nc))return true;p.pop();seen.delete(k)}return false}if(dfs(st[0],st[1]))return out}return [[0,0],[0,1],[0,2],[0,3]]}
function randomizeBoard(){G=Array.from({length:N},()=>Array.from({length:N},()=>Math.floor(Math.random()*4)));for(let i=0;i<120&&path().won;i++)for(let r=0;r<N;r++)for(let c=0;c<N;c++)G[r][c]=Math.floor(Math.random()*4)}
function newGame(){clearInterval(timer);done=false;hint=null;score=BASE;moves=miss=excess=hints=0;rot=new Map();N=CFG[$('diff').value].n;sol=makePath();S=sol[0];E=sol[sol.length-1];randomizeBoard();start=Date.now();$('win').classList.remove('show');$('hint').classList.remove('on');size();draw();upd();loadBest();timer=setInterval(()=>{$('time').textContent=fmt(Math.floor((Date.now()-start)/1000))},300)}
function size(){let wrap=cv.parentElement,w=Math.min(520,wrap.clientWidth||520),cell=Math.max(22,Math.floor((w-20)/N));cv.width=cv.height=cell*N+20;cv.dataset.cell=cell}
function path(){let r=S[0],c=S[1],seen=new Set(),p=[];for(let i=0;i<N*N+2;i++){p.push([r,c]);if(r===E[0]&&c===E[1])return{path:p,won:i>0&&G[r][c]===dir(p[p.length-2],p[p.length-1])};let k=key(r,c);if(seen.has(k))return{path:p,won:false};seen.add(k);let d=G[r][c],nr=r+ST[d][0],nc=c+ST[d][1];if(!inside(nr,nc))return{path:p,won:false};r=nr;c=nc}return{path:p,won:false}}
function pathEndpoint(){let p=path().path;return p[p.length-1]}function endUnlocked(){let last=pathEndpoint();return Math.abs(last[0]-E[0])+Math.abs(last[1]-E[1])===1}
function click(e,ccw){if(done)return;let rect=cv.getBoundingClientRect(),cell=+cv.dataset.cell,r=Math.floor((e.clientY-rect.top-10)/cell),c=Math.floor((e.clientX-rect.left-10)/cell);if(!inside(r,c))return;if(same([r,c],E)&&!endUnlocked())return;let before=path().path,lit=new Set(before.map(p=>key(...p))),k=key(r,c),n=rot.get(k)||0;G[r][c]=ccw?CCW(G[r][c]):CW(G[r][c]);rot.set(k,n+1);moves++;if(!lit.has(k)){miss++;score=Math.max(0,score+MIS)}else if(n>0){excess++;score=Math.max(0,score+EX)}if(hint&&G[hint.r][hint.c]===hint.d){hint=null;$('hint').classList.remove('on')}let p=path();draw();upd();if(p.won)win(p)}
function useHint(){if(done)return;let p=path().path,i=0;while(i<p.length&&i<sol.length&&same(p[i],sol[i]))i++;let idx=Math.max(0,Math.min(i-1,sol.length-2)),a=sol[idx],b=sol[idx+1];hint={r:a[0],c:a[1],d:dir(a,b)};hints++;score=Math.max(0,score+HINT);$('hint').classList.add('on');draw();upd()}
function draw(){let cell=+cv.dataset.cell||50,w=cv.width;x.clearRect(0,0,w,w);x.fillStyle='#1c1c27';round(0,0,w,w,8);let p=path(),lit=new Set(p.path.map(q=>key(...q))),eu=endUnlocked();for(let r=0;r<N;r++)for(let c=0;c<N;c++){let px=10+c*cell,py=10+r*cell;x.fillStyle='#212130';round(px+1,py+1,cell-2,cell-2,5);if(lit.has(key(r,c))){x.fillStyle='rgba(168,224,99,.15)';round(px+1,py+1,cell-2,cell-2,5)}if(hint&&hint.r===r&&hint.c===c){x.fillStyle='rgba(108,92,231,.24)';round(px+1,py+1,cell-2,cell-2,5)}}for(let r=0;r<N;r++)for(let c=0;c<N;c++)cellDraw(r,c,cell,lit.has(key(r,c)),eu);if(hint)hintDraw(cell)}
function cellDraw(r,c,cell,lit,eUnlocked){let cx=10+c*cell+cell/2,cy=10+r*cell+cell/2,isS=same([r,c],S),isE=same([r,c],E),col=isS?'#00cec9':isE?'#fd79a8':lit?'#a8e063':COL[G[r][c]];if(isS||isE)marker(cx,cy,cell,isS,col,isE&&eUnlocked);arrow(cx,cy,G[r][c],cell,col,isS||isE);if(isS||isE){x.fillStyle='#111118';x.font='900 '+Math.max(13,cell*.32)+'px Segoe UI';x.textAlign='center';x.textBaseline='middle';x.fillText(isS?'S':'E',cx,cy)}}
function marker(cx,cy,cell,isS,col,unlocked){x.save();x.strokeStyle=col;x.lineWidth=Math.max(3,cell*.08);x.globalAlpha=isS||unlocked?1:.45;x.beginPath();x.arc(cx,cy,cell*.42,0,Math.PI*2);x.stroke();if(isS||unlocked){x.globalAlpha=.18;x.fillStyle=col;x.beginPath();x.arc(cx,cy,cell*.43,0,Math.PI*2);x.fill()}x.restore()}
function arrow(cx,cy,d,cell,col,big){x.save();x.translate(cx,cy);x.rotate(d*Math.PI/2-Math.PI/2);x.strokeStyle=x.fillStyle=col;x.lineWidth=Math.max(2,cell*(big?.08:.065));x.lineCap='round';x.beginPath();x.moveTo(-cell*.25,0);x.lineTo(cell*.04,0);x.stroke();x.beginPath();x.moveTo(cell*.24,0);x.lineTo(cell*.05,-cell*.115);x.lineTo(cell*.05,cell*.115);x.closePath();x.fill();x.restore()}
function hintDraw(cell){let px=10+hint.c*cell,py=10+hint.r*cell;x.save();x.strokeStyle='#a29bfe';x.lineWidth=3;x.setLineDash([5,4]);x.strokeRect(px+4,py+4,cell-8,cell-8);x.restore();arrow(px+cell/2,py+cell/2,hint.d,cell,'#a29bfe',true)}function round(a,b,c,d,r){x.beginPath();x.moveTo(a+r,b);x.arcTo(a+c,b,a+c,b+d,r);x.arcTo(a+c,b+d,a,b+d,r);x.arcTo(a,b+d,a,b,r);x.arcTo(a,b,a+c,b,r);x.fill()}
function shortestLen(){return Math.abs(S[0]-E[0])+Math.abs(S[1]-E[1])+1}function scoreParts(elapsed,len){let short=shortestLen(),ratio=len/Math.max(1,short),par=CFG[$('diff').value].par,bonus=0;if(ratio>=LP){bonus=LPBASE+Math.max(0,Math.round((len-short*LP)*LPPT));par=Math.round(par*Math.min(LPCAP,Math.max(1,ratio/LP)))}let speed=Math.max(SPDCAP,Math.round(SPD*(1-elapsed/par)));return{short,ratio,par,bonus,speed,long:ratio>=LP}}
function win(p){done=true;clearInterval(timer);let elapsed=Math.floor((Date.now()-start)/1000),parts=scoreParts(elapsed,p.path.length),final=Math.max(0,score+parts.bonus+parts.speed),stars=final>=1100?3:final>=700?2:1,star='★'.repeat(stars)+'☆'.repeat(3-stars),d=$('diff').value;if(!best[d]||final>best[d]){best[d]=final;localStorage.setItem(BEST,JSON.stringify(best))}let lpLine=parts.long?`<div title='Long-path value shown only for routes at least 200% of shortest path.'>Long Path Net: <span class='lp'>${sig(parts.bonus)} pts</span></div>`:'';let parLine=parts.long?` · Long-path par: ${parts.par}s`:'';$('stats').innerHTML=`<div><strong>${final}</strong> pts · <strong>${star}</strong></div><div>Time: ${fmt(elapsed)} · Moves: ${moves}</div><div>Path length: ${p.path.length} (shortest: ${parts.short}, ${Math.round(parts.ratio*100)}%) <strong>${sig(parts.bonus)} pts</strong></div>${lpLine}<div>Speed score: ${sig(parts.speed)}${parLine}</div><div>Misclicks: ${miss} · Excess rotations: ${excess}</div>${hints?`<div>Hints: ${hints} (${sig(hints*HINT)} pts)</div>`:''}`;$('win').classList.add('show');upd()}
function upd(){$('score').textContent=score;$('moves').textContent=moves;let d=$('diff').value;$('best').textContent=best[d]||'--'}function loadBest(){try{best=JSON.parse(localStorage.getItem(BEST)||'{}')}catch{best={}}upd()}
$('new').onclick=newGame;$('next').onclick=newGame;$('diff').onchange=newGame;$('hint').onclick=useHint;cv.onclick=e=>click(e,true);cv.oncontextmenu=e=>{e.preventDefault();click(e,false)};window.onresize=()=>{size();draw()};loadBest();newGame();
